[toolchain]
# 必须和当前的anchor版本匹配, 否则会编译报错. 可以通过anchor --version查看版本.
anchor_version = "0.31.1"   # `anchor-cli` version to use(requires `avm`)
# 必须和当前的solana版本匹配, 否则会编译报错. 可以通过solana --version查看版本.
solana_version = "2.2.14"

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter_program = "2fpCFmXHwtqGmUGEoPdwJjddiGEF7ZWmo2itkmvD6j6K"

[programs.testnet]
counter_program = "2fpCFmXHwtqGmUGEoPdwJjddiGEF7ZWmo2itkmvD6j6K"

[programs.devnet]
counter_program = "2fpCFmXHwtqGmUGEoPdwJjddiGEF7ZWmo2itkmvD6j6K"

[programs.mainnet]
counter_program = "2fpCFmXHwtqGmUGEoPdwJjddiGEF7ZWmo2itkmvD6j6K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "keypairs/wallet/wallet-keypair1.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


