[toolchain]
anchor_version = "0.30.1"    # `anchor-cli` version to use(requires `avm`)
solana_version = "1.18.9" 

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter_program = "ABfrNLYZfKUDu6HhKA9wnoagMr9cYve5VzNkENTJumuL"

[programs.testnet]
counter_program = "973AXy198biaWLGN1VpstU4FHXx74UHhEq4UZQf7SiHm"

[programs.devnet]
counter_program = "973AXy198biaWLGN1VpstU4FHXx74UHhEq4UZQf7SiHm"

[programs.mainnet]
counter_program = "973AXy198biaWLGN1VpstU4FHXx74UHhEq4UZQf7SiHm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "keypairs/wallet/wallet-keypair1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


