[toolchain]
anchor_version = "0.30.1"    # `anchor-cli` version to use(requires `avm`)
solana_version = "1.18.9" 

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter_program = "29yhZZKFaQuwR8qj7Kgaow3f9ptwxGV7QEoEYxsqFiVQ"

[programs.testnet]
counter_program = "29yhZZKFaQuwR8qj7Kgaow3f9ptwxGV7QEoEYxsqFiVQ"

[programs.devnet]
counter_program = "29yhZZKFaQuwR8qj7Kgaow3f9ptwxGV7QEoEYxsqFiVQ"

[programs.mainnet]
counter_program = "29yhZZKFaQuwR8qj7Kgaow3f9ptwxGV7QEoEYxsqFiVQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "keypairs/wallet/wallet-keypair1.json"

[scripts]
test = "npm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


